# Generated by Django 5.2.8 on 2025-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Assinatura válida até'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_assinante',
            field=models.BooleanField(default=False, verbose_name='É Assinante?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone/WhatsApp'),
        ),
    ]
