# Generated by Django 5.2.8 on 2025-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicoconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagem', models.ImageField(blank=True, help_text='Tamanho ideal: 1200x400px', null=True, upload_to='banners/')),
                ('link_botao', models.CharField(blank=True, help_text='Ex: /tools/pdf/ ou https://google.com', max_length=200)),
                ('texto_botao', models.CharField(default='Saiba Mais', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
