# Generated by Django 5.2.8 on 2025-11-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bannerhome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='produtos',
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(blank=True, to='core.produto', verbose_name='Produtos Contratados')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.organizacao', verbose_name='Organização'),
        ),
    ]
