# Generated by Django 5.2.8 on 2025-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
