# Generated by Django 5.2.8 on 2026-01-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso'),
            preserve_default=False,
        ),
    ]
