# Generated by Django 5.2.8 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
