# Generated by Django 5.2.8 on 2025-12-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_fit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='organizacao',
        ),
        migrations.AlterField(
            model_name='plano',
            name='duracao_meses',
            field=models.IntegerField(choices=[(1, 'Mensal (1 Mês)'), (3, 'Trimestral (3 Meses)'), (6, 'Semestral (6 Meses)'), (12, 'Anual (12 Meses)')], help_text='1=Mensal, 3=Trimestral, etc'),
        ),
    ]
