# Generated by Django 5.2.8 on 2026-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_fit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Plano'),
        ),
    ]
