# Generated by Django 5.2.8 on 2025-12-06 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_fit', '0003_alter_templatecontrato_texto_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='assinatura_imagem',
            field=models.TextField(blank=True, help_text='Imagem Base64 da assinatura', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ip_assinatura',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='token_assinatura',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente Assinatura'), ('ENVIADO_EMAIL', 'Enviado p/ Assinatura (E-mail)'), ('ASSINADO_DIGITAL', 'Assinado Digitalmente (Email)'), ('ASSINADO_PRESENCIAL', 'Assinado Presencialmente (Tablet)'), ('ASSINADO_PAPEL', 'Assinado no Papel'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado (Fim do Prazo)')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor FINAL fechado', max_digits=10),
        ),
    ]
