# Generated by Django 5.2.8 on 2025-12-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriafinanceira',
            options={'ordering': ['tipo', 'categoria_pai__nome', 'nome'], 'verbose_name': 'Categoria Financeira', 'verbose_name_plural': 'Categorias Financeiras'},
        ),
        migrations.RemoveField(
            model_name='categoriafinanceira',
            name='organizacao',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='organizacao',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='organizacao',
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financeiro_fit.categoriafinanceira', verbose_name='Categoria Pai'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
